### ISSUE TITLE
ImbalancedDatasetSampler

### ISSUE THREAD

**Issue by sustechzx** [XuJ1E/PATER#1]
Hello, would you like to answer me a question, where is the ImbalancedDatasetSampler?

**Comment by XuJ1E** [comment]
we have import ImbalancedDatasetSampler function from torchsampler in "main.py" file> Hello, would you like to answer me a question, where is the ImbalancedDatasetSampler?

**Comment by sustechzx** [comment]
I see. Thank you for your kindness!



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/12/2024 15:45 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [XuJ1E/PATER] ImbalancedDatasetSampler (Issue #1) |

we have import ImbalancedDatasetSampler function from torchsampler in "main.py" file> Hello, would you like to answer me a question, where is the ImbalancedDatasetSampler?
